spring:
  application:
    name: authorization

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authorization:8081/api/auth/.well-known/jwks.json
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8000/api/auth/login/oauth2/code/google}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery:8761/eureka}

server:
  port: ${PORT:8081}

jwt:
  key:
    private: ${RSA_PRIVATE}
    public: ${RSA_PUBLIC}

urls:
  gateway: ${GATEWAY_URL:http://localhost:8000}

logging:
  level:
    org:
      springframework:
        security: TRACE
        web: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
